/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  WhiteListInterface,
  WhiteListInterfaceInterface,
} from "../../interfaces/WhiteListInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "whiteListedAddresses",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class WhiteListInterface__factory {
  static readonly abi = _abi;
  static createInterface(): WhiteListInterfaceInterface {
    return new utils.Interface(_abi) as WhiteListInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WhiteListInterface {
    return new Contract(address, _abi, signerOrProvider) as WhiteListInterface;
  }
}
