/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Komnou__factory } from "./Komnou__factory";
export { WhiteList__factory } from "./WhiteList__factory";
